### ISSUE TITLE
Infinite error loop when adding a new asset

### ISSUE THREAD

**Issue by tylerdq** [wichtounet/budgetwarrior#32]
When I use `budget asset add` and hit Enter after typing the name of the new asset, I get the error message `The distribution must account to 100%` infinitely printing until I Ctrl+C. Then I get the below messages:

```
Loguru caught a signal: SIGINT
Stack trace:
11      0x55c241007355 budget(+0x26355) [0x55c241007355]
10      0x7ffbb028fd8a __libc_start_main + 138
9       0x7ffbb028fcd0 /usr/lib/libc.so.6(+0x27cd0) [0x7ffbb028fcd0]
8       0x55c241006080 budget(+0x25080) [0x55c241006080]
7       0x55c241064913 budget(+0x83913) [0x55c241064913]
6       0x55c241053d3f budget(+0x72d3f) [0x55c241053d3f]
5       0x7ffbb06a6032 std::ostream::put(char) + 226
4       0x7ffbb02ec353 _IO_file_overflow + 259
3       0x7ffbb02ebe19 _IO_do_write + 25
2       0x7ffbb02eb014 /usr/lib/libc.so.6(+0x83014) [0x7ffbb02eb014]
1       0x7ffbb02ecd4d _IO_file_write + 45
0       0x7ffbb036c034 write + 20
2023-10-27 09:49:16.048 (   2.649s) [main thread     ]                       :0     FATL| Signal: SIGINT
```

I may be missing something required to correctly set up assets, but in either case perhaps the application could exit after printing the error once.

**Comment by wichtounet** [comment]
Interesting. I am guessing you don't have any asset class. You must first add asset class with `budget asset class add`. 
I will fix the infinite loop.

Sorry about that, it's been a while since anybody onboard.

**Comment by tylerdq** [comment]
Thanks for the tip. I successfully added an asset class called "Cash" but now when I use any of the below commands I get `"" is not a valid bool`:

- `budget`
- `budget overview`
- `budget asset`
- `budget asset add`

**Comment by wichtounet** [comment]
I have pushed a fix for that again :) 

I have added many new features and tested them only on the web application, it seems, so there are some missing pieces in the console part. Let's hope there are not too many of them.

**Comment by tylerdq** [comment]
I pulled the latest commits and recompiled but I still get the same error when running those 4 commands.

**Comment by wichtounet** [comment]
Can you run `cat ~/.budget/asset_classes.data`? I can't reproduce your issue anymore. 

Then, you can `rm  ~/.budget/asset_classes.data` and then try `budget asset class add`

**Comment by tylerdq** [comment]
Sure thing, `cat ~/.budget/asset_classes.data` returned:

```
2
1:193CEDF9-C083-4A00-A33F-1BD658A3325E:Cash:
```

The other commands did the trick for me and I can use the program again. Thank you!

**Comment by wichtounet** [comment]
Even with your content, I could not reproduce the issue but at least you have a working version now 👍
